import {
  AuthError,
  createSessionRequest,
  createSkill,
  deleteSession,
  deleteSkill,
  fetchBuiltInProfileDefinition,
  fetchHistory,
  fetchProfiles,
  fetchSkill,
  fetchSkills,
  fetchTools,
  generateSkillContent,
  sendMessage,
  testMcpConnections,
  updateSkill,
} from './client';

export const apiExportContract = {
  AuthError,
  createSessionRequest,
  createSkill,
  deleteSession,
  deleteSkill,
  fetchBuiltInProfileDefinition,
  fetchHistory,
  fetchProfiles,
  fetchSkill,
  fetchSkills,
  fetchTools,
  generateSkillContent,
  sendMessage,
  testMcpConnections,
  updateSkill,
};